### ISSUE TITLE
v0.1.0

### ISSUE THREAD

**Issue by armanbilge** [typelevel/toolkit#4]
Anything we wanna do prior to a first release? :)

**Comment by armanbilge** [comment]
Yolo, let's do v0.0.1 with what we've got :) and talk about v0.1.0.

**Comment by TonioGela** [comment]
> Yolo, let's do v0.0.1 with what we've got :) and talk about v0.1.0.

v0.0.2 landed in no-time :D

**Comment by TonioGela** [comment]
Maybe finalizing the included libraries list and adding an example for each is enough for our first minor release?

**Comment by armanbilge** [comment]
So first of all, It's all pretty arbitrary :) it would probably be fine.

But ... one thing to keep in mind is, we don't know yet how the scala-cli integration may work. It may require us to publish under a different artifact name (I heard some murmur of just "kit" instead of "toolkit" for example).

Another thing to keep in mind is that although I believe Scala Toolkit will be going to 1.0.0 in the near future, we technically won't be able to until http4s goes to 1.0.0. So that might be a while yet.

**Comment by armanbilge** [comment]
I propose we release v0.1.0 to coordinate with the announcement blog post.
- https://github.com/scala/scala-lang/pull/1512

**Comment by armanbilge** [comment]
https://github.com/typelevel/toolkit/releases/tag/v0.1.0
