### ISSUE TITLE
Compiling for scala-native throws `scala.MatchError`

### ISSUE THREAD

**Issue by andrzejressel** [typelevel/toolkit#49]
I've tried using this toolkit for my Scala Native project, but it fails with
```
scala.MatchError: 16 (of class java.lang.Integer)
```

for both scala-cli and sbt on all platforms:
- https://github.com/andrzejressel/typelevel-toolkit-native/actions/runs/5272627423
- https://github.com/andrzejressel/typelevel-toolkit-native/actions/runs/5272627424

**Comment by andrzejressel** [comment]
Well, now I got even more cryptic `scala.scalanative.util.UnreachableException$`

**Comment by armanbilge** [comment]
Wait a minute, I was stupid: the _latest_ Scala Native is 0.4.14. Bump to that. 0.4.13 was bugged, which is why you get that error

**Comment by andrzejressel** [comment]
Seems to be working fine now, thanks a lot
