### ISSUE TITLE
Drop Scala 2.12

### ISSUE THREAD

**Issue by armanbilge** [typelevel/toolkit#6]
Scala Toolkit supports 2.12. All of our libraries do so far, so it's not any extra effort to do it here.

But, why. Here you go @sethtisue 😜

**Comment by TonioGela** [comment]
Since we're at `0.0.2` we can declare that `_2.12::0.0.1` and `_2.12::0.0.2` were build misconfigurations ¯\_(ツ)_/¯ 😇

**Comment by SethTisue** [comment]
I suggested the same for the Scala Toolkit over at https://github.com/VirtusLab/toolkit/issues/3 . not sure how to interpret the silence, maybe they're discussing it internally?

**Comment by TonioGela** [comment]
Okay, we can delegate the decision to them and decide after receiving an answer. If the toolkit won't support Scala 2.12 anymore, then there's no reason for us to do the same (even taking in consideration the fact that the toolkit can be used as a vanilla dependency in sbt/mill)

**Comment by armanbilge** [comment]
Scala Toolkit is dropping 2.12, so we can too.

https://github.com/scala/toolkit/issues/3#issuecomment-1535115868
