### ISSUE TITLE
Example script doesn't print anything

### ISSUE THREAD

**Issue by arosien** [typelevel/toolkit#9]
I ran the example code from the README and it doesn't print anything:
```
➜  toolkit git:(main) ✗ scala-cli toolkit.sc
Compiling project (Scala 3.2.2, JVM)
Compiled project (Scala 3.2.2, JVM)
➜  toolkit git:(main) ✗ 
```

I'm not sure if this is because of scala-cli or Cats Effect.

**Comment by armanbilge** [comment]
The file should be named `toolkit.scala`, not `*.sc`.

**Comment by arosien** [comment]
I hate computers.

**Comment by arosien** [comment]
https://typelevel.org/cats-effect/docs/faq#scala-cli speaks to this tragic situation.
